### PR TITLE
Rules for building tesseract 5.0.0

### PR DESCRIPTION
**Pull request by AlexanderP**

### CODE REVIEW

**Comment by AlexanderP** [comment]
@stweil @Shreeshrii look at the Debian rules for tesseract 5.0.0

**Comment by stweil** [comment]
It looks good, thank you.

**Comment by Shreeshrii** [comment]
@stweil The traineddata files in tessdata, tessdata_best, tessdata_fast are
the same as used for version 4.00/4.1.

Will this change lead to multiple copies of traineddata being installed?

Is a new release of traineddata files expected from Google?

**Comment by stweil** [comment]
Yes, the traineddata files did not change. But some config files changed in release 5, so it is necessary to have a new tessdata directory. As long as there is only one version of Tesseract installed, there won't be multiply copies of traineddata.

I don't know whether Google will make a new release of traineddata files, but perhaps we'll get updates and new traineddata from community contributors.

**Comment by Shreeshrii** [comment]
Thanks, @stweil, for the clarification.

Thanks, Alex!

**Comment by AlexanderP** [comment]
Thanks!

**Comment by AlexanderP** [comment]
Created a new ppa https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-devel for tesseract 5.0.0

**Comment by Shreeshrii** [comment]
Thanks,.Alex. it is useful to have ppa for with the code for 5.0.0 .

I suggest that you update the ppa description with newer text about tesseract. You can take it from readme.md in tesseract project.

**Comment by Shreeshrii** [comment]
Suggested description for new ppa https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-devel for tesseract 5.0.0.

>This package contains an OCR engine - libtesseract and a command line program - tesseract. The development version available here (currntly 5.0.0 Alpha) is better in many aspects (functionality, speed, stability) but is not 100 % API compatible with version 4.0. Tesseract 4 added a new neural net (LSTM) based OCR engine which is focused on line recognition, but also still supports the legacy Tesseract OCR engine of Tesseract 3 which works by recognizing character patterns. Compatibility with Tesseract 3 is enabled by using the Legacy OCR Engine mode (--oem 0). It also needs traineddata files which support the legacy engine, for example those from the tessdata repository. Tesseract has unicode (UTF-8) support, and can recognize more than 100 languages "out of the box". Tesseract supports various output formats: plain text, hOCR (HTML), PDF, invisible-text-only PDF, TSV. The master branch also has experimental support for ALTO (XML) output.

@stweil is this ok?

**Comment by AlexanderP** [comment]
@Shreeshrii Thanks

**Pull request merged**
