### PR TITLE
Add new Debian package for equ.traineddata

### PR DESCRIPTION
**Pull request by stweil**
Fix also some typos.

### CODE REVIEW

**Comment by AlexanderP** [comment]
Thanks! 

Since "equ.traineddata" is not at https://github.com/tesseract-ocr/tessdata_fast.
I will create a separate reps for it.

**Comment by stweil** [comment]
It is in https://github.com/tesseract-ocr/tessdata. Maybe it will be added to https://github.com/tesseract-ocr/tessdata_fast as well.

**Comment by AlexanderP** [comment]
> It is in https://github.com/tesseract-ocr/tessdata. Maybe it will be added to https://github.com/tesseract-ocr/tessdata_fast as well.

that would be great

**Comment by AlexanderP** [comment]
> It is in https://github.com/tesseract-ocr/tessdata. Maybe it will be added to https://github.com/tesseract-ocr/tessdata_fast as well.

@stweil  Will it be added to the repository? 
To understand how to upload a package in debian.

**Pull request merged**
